// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdqumoadlanetckyxzow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcXVtb2FkbGFuZXRja3l4em93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODU5NTUsImV4cCI6MjA2NTQ2MTk1NX0.XqGQyL4SyPqXPXOj92jNIBrs8yDO_mpb9F7AOHFrfi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);